### PR TITLE
WIP: Include photos and bios

### PR DESCRIPTION
**Pull request by russelldj**
I added the photos and bios from the confirmed speakers. This is still work in progress 1) the images aren't showing up correctly for me in my local build and 2) the formatting looks pretty gross when just rendered in markdown. I just wanted to get this up as a start.

### CODE REVIEW

**Comment by youngdjn** [comment]
Thanks so much for doing this @russelldj ! I think you should insert images either like this: https://docs.hugoblox.com/reference/markdown/#single-image
or
like this: https://github.com/open-forest-observatory/ofo-website-3/blob/aedb8f135660352fd2f80a991f91cdd85bc09e3f/content/tools/index.md?plain=1#L45

with paths relative to `assets/media/`

**Comment by russelldj** [comment]
Thanks! That was silly, I was reference stuff from our MKdocs sites. I think the formatting looks a bit off, but it could be merged now. Specifically, I found that I couldn't control the height of the images, only the width. And I was thinking it might look better for the image to be to the left of the bio, rather than above, but I wasn't finding a simple way to do that.

**Comment by youngdjn** [comment]
Yes this may unfortunately be a limitation. [Here is one hack](https://discourse.gohugo.io/t/handling-images-size-aligning/1940), but probably not worth it. That CSS bit would get added put in a new file `assets/scss/custom.scss`.

Regarding width/height, you could do a similar hack I used for the FOCAL website to make the round image on the home page, where you put the following in the markdown where the image should show up (specifically the `class="round"`):

```
        {{< figure src="flagged-seedlings-square.jpg" class="round" >}}
```

and put the following in the `assetts/scss/custom.scss`:

```
.round > * img{
    border-radius: 50%;
    width: 350px;
    height: 100%;
    object-fit: cover;
    object-position: 90% 0;
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```

**Comment by russelldj** [comment]
I didn't wrap the text, I just left aligned the photos above each bio. I think it's good enough to merge, especially with the narrow columns.

**Review by youngdjn — APPROVED** [review]
Nice, I agree it looks good!

**Pull request merged**
